name: Release Tag

on:
  push:
    branches: ['main']

concurrency:
  group: release-tag
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tag:
    name: Create Tag from package.json
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TAG_PAT }}

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check and Push Tag
        env:
          RELEASE_TAG_PAT: ${{ secrets.RELEASE_TAG_PAT }}
        run: |
          TAG=${{ steps.get_version.outputs.version }}

          if [ -z "$RELEASE_TAG_PAT" ]; then
            echo "RELEASE_TAG_PAT is not set"
            exit 1
          fi

          git fetch --tags
          if git ls-remote --tags origin "$TAG" | grep -q "$TAG"; then
            echo "‚ö†Ô∏è Tag $TAG already exists. Skipping..."
            exit 0
          fi

          echo "üöÄ Creating new tag: $TAG"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push "https://${RELEASE_TAG_PAT}@github.com/${{ github.repository }}.git" "$TAG"
